TRUNCATE TABLE "DimDate" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DimProducts" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DimRiders" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DimUsers" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "FactSales" RESTART IDENTITY CASCADE;
